#!/bin/bash
# ---------------------------------------------------------------------------
# Alamos AMweb Kiosk Autostart Setup for Raspberry Pi 4 (Raspberry Pi OS
# Bookworm, 64-bit, Desktop edition).
#
# What this does:
#   1. Installs Chromium, Noto color emoji font (Alamos requirement), and
#      a few helpers.
#   2. Disables screen blanking / screensaver (raspi-config).
#   3. Creates a launcher script (~/amweb-kiosk.sh) that:
#        - waits for network,
#        - launches Chromium in --kiosk on the AMweb URL,
#        - restarts Chromium if it crashes,
#        - uses a dedicated, persistent user-data-dir so the AMweb
#          login (Passwort + Verschlüsselungspasswort) survives reboots.
#   4. Registers the launcher in labwc autostart (default compositor on
#      current Raspberry Pi OS Bookworm). Also writes a Wayfire fallback,
#      so this works on both compositors.
#
# Based on the official Alamos documentation:
#   https://alamos-support.atlassian.net/wiki/spaces/documentation/pages/2496790534/Autostart+AMweb
#   https://alamos-support.atlassian.net/wiki/spaces/documentation/pages/2710208513/AMweb+Kioskmode+PWA+und+mehrere+Bildschirme
#   https://alamos-support.atlassian.net/wiki/spaces/documentation/pages/2390622209/Systemvoraussetzungen+und+Einstellungen+f%C3%BCr+den+Browser
#
# Usage:
#   1. Flash Raspberry Pi OS Bookworm (64-bit, Desktop) to an SD card.
#   2. Boot, finish the welcome wizard, connect to network.
#   3. Copy this script to the Pi (e.g. into the home folder).
#   4. Open a Terminal and run:
#        chmod +x setup-amweb-kiosk.sh
#        ./setup-amweb-kiosk.sh
#      You will be prompted for your AMweb URL.
#   5. After the reboot, log in to AMweb ONCE (Passwort +
#      Verschlüsselungspasswort). After that, every power-loss / reboot
#      will bring the AMweb back up automatically, already logged in.
# ---------------------------------------------------------------------------

set -euo pipefail

# ---------- 0. Sanity checks ----------------------------------------------
if [[ $EUID -eq 0 ]]; then
    echo "Please run this script as the normal 'pi' (or your own) user, NOT as root."
    echo "It will call sudo where needed."
    exit 1
fi

USER_NAME="$(id -un)"
USER_HOME="$HOME"

echo "============================================================"
echo " Alamos AMweb Kiosk Setup"
echo " User:   $USER_NAME"
echo " Home:   $USER_HOME"
echo "============================================================"

# ---------- 1. Ask for the AMweb URL --------------------------------------
DEFAULT_URL="https://web.alarmmonitor.de/REPLACE-WITH-YOUR-AMWEB-ID"
read -rp "Enter your full AMweb URL [$DEFAULT_URL]: " AMWEB_URL
AMWEB_URL="${AMWEB_URL:-$DEFAULT_URL}"

if [[ "$AMWEB_URL" == *"REPLACE-WITH-YOUR-AMWEB-ID"* ]]; then
    echo "ERROR: You must enter your real AMweb URL (the one with your AccessId)."
    exit 1
fi

echo "Using AMweb URL: $AMWEB_URL"

# ---------- 2. Update packages and install dependencies -------------------
echo "[1/5] Updating package lists and installing dependencies..."
sudo apt-get update
sudo apt-get install -y \
    chromium-browser \
    fonts-noto-color-emoji \
    unclutter \
    xdotool \
    wlr-randr || true

# ---------- 3. Disable screen blanking ------------------------------------
echo "[2/5] Disabling screen blanking / screensaver..."
# raspi-config nonint do_blanking: 0 = enable blanking, 1 = disable blanking
sudo raspi-config nonint do_blanking 1 || true

# ---------- 4. Write the kiosk launcher script ----------------------------
echo "[3/5] Writing the kiosk launcher script to $USER_HOME/amweb-kiosk.sh ..."
LAUNCHER="$USER_HOME/amweb-kiosk.sh"
cat > "$LAUNCHER" <<EOF
#!/bin/bash
# AMweb kiosk launcher - generated by setup-amweb-kiosk.sh
# Do not edit this line:
AMWEB_URL="$AMWEB_URL"

# Wait for the desktop to settle
sleep 5

# Wait for network (max 60s). We resolve the AMweb host.
HOST="\$(echo "\$AMWEB_URL" | awk -F/ '{print \$3}')"
for i in \$(seq 1 60); do
    if getent hosts "\$HOST" >/dev/null 2>&1; then
        break
    fi
    sleep 1
done

# Belt and braces: try to keep the screen on under Wayland too.
# (raspi-config already disables blanking; this is a no-op fallback.)
if command -v wlr-randr >/dev/null 2>&1; then
    wlr-randr 2>/dev/null | grep -oE '^[A-Za-z0-9-]+' | head -n1 | \\
        xargs -I{} wlr-randr --output {} --on 2>/dev/null || true
fi

# Dedicated, persistent profile so the AMweb login (password +
# encryption password) survives reboots.
PROFILE_DIR="\$HOME/.config/chromium-amweb"
mkdir -p "\$PROFILE_DIR"

# Suppress the "restore session?" yellow bar and the "Chrome wasn't
# shut down properly" bubble after a power loss (Alamos KB).
PREF_FILE="\$PROFILE_DIR/Default/Preferences"
if [[ -f "\$PREF_FILE" ]]; then
    # Tell Chromium the last session ended cleanly.
    sed -i 's/"exit_type":"Crashed"/"exit_type":"Normal"/g' "\$PREF_FILE" 2>/dev/null || true
    sed -i 's/"exited_cleanly":false/"exited_cleanly":true/g' "\$PREF_FILE" 2>/dev/null || true
fi

# Restart Chromium forever if it ever exits.
while true; do
    chromium-browser \\
        --kiosk \\
        --start-fullscreen \\
        --noerrdialogs \\
        --disable-infobars \\
        --disable-session-crashed-bubble \\
        --hide-crash-restore-bubble \\
        --no-first-run \\
        --no-default-browser-check \\
        --disable-features=TranslateUI \\
        --check-for-update-interval=31536000 \\
        --autoplay-policy=no-user-gesture-required \\
        --ozone-platform-hint=auto \\
        --user-data-dir="\$PROFILE_DIR" \\
        "\$AMWEB_URL"
    # If Chromium dies, wait a moment and relaunch.
    sleep 5
done
EOF
chmod +x "$LAUNCHER"

# ---------- 5. Register launcher in labwc + Wayfire autostart --------------
echo "[4/5] Registering autostart for labwc and Wayfire..."

# --- labwc (default on current Bookworm for both Pi 4 and Pi 5)
LABWC_DIR="$USER_HOME/.config/labwc"
LABWC_AUTOSTART="$LABWC_DIR/autostart"
mkdir -p "$LABWC_DIR"
touch "$LABWC_AUTOSTART"
if ! grep -q "amweb-kiosk.sh" "$LABWC_AUTOSTART"; then
    {
        echo ""
        echo "# Alamos AMweb kiosk autostart"
        echo "$LAUNCHER &"
    } >> "$LABWC_AUTOSTART"
fi
chmod +x "$LABWC_AUTOSTART"

# --- Wayfire (older Bookworm releases used this as default)
WAYFIRE_INI="$USER_HOME/.config/wayfire.ini"
if [[ -f "$WAYFIRE_INI" ]]; then
    if ! grep -q "^amweb" "$WAYFIRE_INI"; then
        # Make sure we have [autostart] section
        if ! grep -q "^\[autostart\]" "$WAYFIRE_INI"; then
            echo "" >> "$WAYFIRE_INI"
            echo "[autostart]" >> "$WAYFIRE_INI"
        fi
        sed -i "/^\[autostart\]/a amweb = $LAUNCHER" "$WAYFIRE_INI"
    fi
    # Disable Wayfire idle/blanking
    if ! grep -q "^idle_timeout" "$WAYFIRE_INI"; then
        if grep -q "^\[idle\]" "$WAYFIRE_INI"; then
            sed -i "/^\[idle\]/a dpms_timeout = 0\nscreensaver_timeout = 0" "$WAYFIRE_INI"
        else
            {
                echo ""
                echo "[idle]"
                echo "dpms_timeout = 0"
                echo "screensaver_timeout = 0"
            } >> "$WAYFIRE_INI"
        fi
    fi
fi

# --- XDG-autostart fallback (older LXDE / X11 sessions)
XDG_DIR="$USER_HOME/.config/autostart"
mkdir -p "$XDG_DIR"
cat > "$XDG_DIR/amweb-kiosk.desktop" <<EOF
[Desktop Entry]
Type=Application
Name=Alamos AMweb Kiosk
Exec=$LAUNCHER
X-GNOME-Autostart-enabled=true
NoDisplay=false
Terminal=false
EOF

# ---------- 6. Done -------------------------------------------------------
echo "[5/5] Done."
echo ""
echo "============================================================"
echo " Setup complete."
echo ""
echo " Next steps:"
echo "   1. Reboot:   sudo reboot"
echo "   2. After boot the AMweb opens automatically in Chromium."
echo "      Log in ONCE with your Passwort + Verschlüsselungspasswort."
echo "      (This is the password you defined when you created the"
echo "       AMweb in FE2.)"
echo "   3. From then on, every restart / power loss will bring the"
echo "      AMweb back up - already logged in - because Chromium keeps"
echo "      the session in $USER_HOME/.config/chromium-amweb/."
echo ""
echo " To exit kiosk mode: press Ctrl+F4 or Alt+F4."
echo " To change the URL later: edit $LAUNCHER (top line)."
echo "============================================================"
